---
- name: invoke the role for /etc/iaac
  hosts: iaas
  become: yes
  roles:
    - create_empty_file
- name: invoke the role for /etc/iaac for defining virable
  hosts: all
  become: yes
  roles:   
    - define_content_variable
  tasks:
    - name: print in registered variables and hostname
      debug:
        msg: "System hostname: {{ inventory_hostname }} has issue content: {{ resultIssue.stdout }}"
